---
title: "USA Severe Weather Events: The Economic and Humanitarian Impact"
date: 2019-09-08
tags: [Data Cleaning, Data Visualisation]
header:
  image: "/images/Storm images/storm.jpg"
excerpt: "Data Cleaning, Data Visualisation"
---

Introduction
============

Severe weather events have the potential to inflict damages, injuries, and loss of life on an enormous scale; minimising their impact is vital. To that end, understanding the extent to which different severe weather events can have these effects, can help inform damage limiting measures such as evacuation and diaster relief appropriation.

Aims
====

This analysis will focus on the economic and humanitarian impact of severe weather events in the USA. In particular, it will aim to answer the following:

*1. Across the United States, which types of events are most harmful with respect to population health?*

*2. Across the United States, which types of events have the greatest economic consequences?*

Data
====

The data comes from the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. This database contains information on a number of severe weather events in US including fatalities, injuries, crop damages and property damages. Information for this dataset can be found [here](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf)

We begin by loading the required packages.

``` r
# Load packages
require(ggplot2, warn.conflicts = F, quietly = T)
require(plyr, warn.conflicts = F, quietly = T)
require(dplyr, warn.conflicts = F, quietly = T)
require(stringdist, warn.conflicts = F, quietly = T)
require(data.table, warn.conflicts = F, quietly = T)
```

We now download and unzip the storm data set into the working directory.

``` r
#Download and load data
path <- getwd()
url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
download.file(url, destfile = paste(path, 'repdata%2Fdata%2FStormData.csv.bz2', sep = "/"))
RawData <- read.csv("repdata%2Fdata%2FStormData.csv.bz2")
```

Data Cleaning
=============

This dataset requires significant work to clean and manipulate it into a form which will allow us to answer the two questions set out in the aims section.

To begin, note that we are only interested in data pertaining to injuries, deaths and damages so we drop any irrelevant columns.

``` r
#Select only relevant columns
stormData <- select(RawData, EventType = EVTYPE, Fatalities = FATALITIES, Injuries = INJURIES, PropertyDamage = PROPDMG, PropertyDamageExponent = PROPDMGEXP, CropDamage = CROPDMG, CropDamageExponent = CROPDMGEXP, Date = BGN_DATE)
```

Let's take an initial look at our data.

``` r
str(stormData)
```

    ## 'data.frame':    902297 obs. of  8 variables:
    ##  $ EventType             : Factor w/ 985 levels "   HIGH SURF ADVISORY",..: 834 834 834 834 834 834 834 834 834 834 ...
    ##  $ Fatalities            : num  0 0 0 0 0 0 0 0 1 0 ...
    ##  $ Injuries              : num  15 0 2 2 2 6 1 0 14 0 ...
    ##  $ PropertyDamage        : num  25 2.5 25 2.5 2.5 2.5 2.5 2.5 25 25 ...
    ##  $ PropertyDamageExponent: Factor w/ 19 levels "","-","?","+",..: 17 17 17 17 17 17 17 17 17 17 ...
    ##  $ CropDamage            : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ CropDamageExponent    : Factor w/ 9 levels "","?","0","2",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ Date                  : Factor w/ 16335 levels "1/1/1966 0:00:00",..: 6523 6523 4242 11116 2224 2224 2260 383 3980 3980 ...

The dataset contains 902297 observations of the following 8 variables:

1.  EventType: The type of severe weather event
2.  Fatalities: The number of deaths the event caused
3.  Injuries: The number of injures the event caused
4.  PropertyDamage: The amount of damage to property in US dollars. This is combined with the exponent to give the real amount.
5.  PropertyDamageExponent: The multiplier for calculating the real terms amount.
6.  CropDamage: The amount of damage to crops in US dollars. This is combined with the exponent to give the real amount.
7.  CropDamageExponent: The multiplier for calculating the real terms amount.
8.  Date: When the severe weather event happened

Note, to calculate the real amount of damages use the following formula:

Real Amount = Damage \* (10^DamageExponent)

The [documentation](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf) for the dataset defines 55 events however we observe 985 event types in our data. This is due to discrepanceis in the use of uppercase and lowercase letters as well as non-official words and phrases being used. One way to begin dealing with this is to only look at those cases where there were non-zero fatalities, injuries, property or crop damage.

``` r
stormData <- stormData %>% filter(PropertyDamage > 0 | CropDamage > 0 | Fatalities > 0 | Injuries > 0)
```

Data collection on all 55 events only began in January 1996. Thus to prevent the data being skewed towards events collected prior to this date, we filter the data to only entries data since then.

``` r
stormData$Date <- as.Date(stormData$Date, format = "%M/%d/%Y")
stormData <- stormData %>% filter(stormData$Date >= "1996-01-01")
```

Aggregation
-----------

We now combine the damages and exponent columns to create real crop and property damage columns. We use the methodology laid out [here](https://rstudio-pubs-static.s3.amazonaws.com/58957_37b6723ee52b455990e149edde45e5b6.html)

``` r
#Rename exponents
levels(stormData$PropertyDamageExponent)[1] <- 0
stormData$PropertyDamageExponent <- revalue(stormData$PropertyDamageExponent, c("h" = 2, "H" = 2, "K" = 3, "m" = 6, "M" = 6, "B" = 9, "+" = 1, "-" = 0, "?" = 0))
levels(stormData$CropDamageExponent)[1] <- 0
stormData$CropDamageExponent <- revalue(stormData$CropDamageExponent, c("K" = 3, "k" = 3, "m" = 6, "M" = 6, "B" = 9, "?" = 0))

#Create columns for property damage and crop damage
stormData <- mutate(stormData, RealPropertyDamage = PropertyDamage * (10^as.numeric(as.character(PropertyDamageExponent))))
stormData <- mutate(stormData, RealCropDamage = CropDamage * (10^as.numeric(as.character(CropDamageExponent))))
stormData <- stormData[, !(names(stormData) %in% c("PropertyDamage", "PropertyDamageExponent", "CropDamageExponent", "CropDamage"))]
```

In addition we create a variables encompassing the total injuries/fatalities and total damages.

``` r
#Create columns for total injuries/fatalities and damage per event type
stormData <- mutate(stormData, TotalInjuriesFatalities = Fatalities + Injuries)
stormData <- mutate(stormData, TotalDamage = RealPropertyDamage + RealCropDamage)
```

Event Matching
--------------

Let's take another look at our data.

``` r
str(stormData)
```

    ## 'data.frame':    197876 obs. of  8 variables:
    ##  $ EventType              : Factor w/ 985 levels "   HIGH SURF ADVISORY",..: 972 834 856 856 856 359 856 856 856 153 ...
    ##  $ Fatalities             : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ Injuries               : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ Date                   : Date, format: "1996-09-06" "1996-09-11" ...
    ##  $ RealPropertyDamage     : num  380000 100000 3000 5000 2000 400000 12000 8000 12000 75000 ...
    ##  $ RealCropDamage         : num  38000 0 0 0 0 0 0 0 0 0 ...
    ##  $ TotalInjuriesFatalities: num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ TotalDamage            : num  418000 100000 3000 5000 2000 400000 12000 8000 12000 75000 ...

We still need to match each event type to the correct event type of the 55 listed in the documentation. First we drop all unused events.

``` r
stormData <- droplevels(stormData)
```

Next we create the variable events which contains the official list of 55 event types. We also tidy the events variable as well as the list of event types in our dataset by removing white space.

``` r
events <- strsplit(c("Astronomical Low Tide Z
                     Avalanche Z
                     Blizzard Z
                     Coastal Flood Z
                     Cold/Wind Chill Z
                     Debris Flow C
                     Dense Fog Z
                     Dense Smoke Z
                     Drought Z
                     Dust Devil C
                     Dust Storm Z
                     Excessive Heat Z
                     Extreme Cold/Wind Chill Z
                     Flash Flood C
                     Flood C
                     Frost/Freeze Z
                     Funnel Cloud C
                     Freezing Fog Z
                     Hail C
                     Heat Z
                     Heavy Rain C
                     Heavy Snow Z
                     High Surf Z
                     High Wind Z
                     Hurricane (Typhoon) Z
                     Ice Storm Z
                     Lake-Effect Snow Z
                     Lakeshore Flood Z
                     Lightning C
                     Marine Dense Fog M
                     Marine Hail M
                     Marine Heavy Freezing Spray M
                     Marine High Wind M
                     Marine Hurricane/Typhoon M
                     Marine Lightning M
                     Marine Strong Wind M
                     Marine Thunderstorm Wind M
                     Marine Tropical Depression M
                     Marine Tropical Storm M
                     Rip Current Z
                     Seiche Z
                     Sleet Z
                     Sneaker Wave Z
                     Storm Surge/Tide Z
                     Strong Wind Z
                     Thunderstorm Wind C
                     Tornado C
                     Tropical Depression Z
                     Tropical Storm Z
                     Tsunami Z
                     Volcanic Ash Z
                     Waterspout M
                     Wildfire Z
                     Winter Storm Z
                     Winter Weather Z"), split = " Z\n| M\n| C\n| Z")
events <- sapply(events, FUN = trimws, which = c("both"))
levels(stormData$EventType) <- sapply(levels(stormData$EventType), FUN = trimws, which = c("both"))
```

We deal with the events in our dataset for which there is an exact match (non-case sensitive) in the official list of events.

``` r
for(i in 1:length(events)){
  levels(stormData$EventType) <- gsub(events[i], events[i], levels(stormData$EventType), ignore.case = TRUE)
}
```

We note that the abbreviation TSTM is used to mean thunderstorm so we adjust for that.

``` r
levels(stormData$EventType) <- gsub("TSTM .*|Thunderstorm Wind .*", events[46], levels(stormData$EventType), ignore.case = TRUE)
```

To match the remaining events we implement the amatch function which looks for partial matches between the lists of events in the database and the official list of events. The extent to which different words are be matched during this process is controlled using the argument maxDist. That is, the for a small value, only words or phrases which are very similar to each other will be matched. Conversely, for a large value, words or phrases which are very different may be matched with each other. Thus using this algorithm is a balancing act between having a large enough value of maxDist to ensure enough of the events are matched, but not so large that many events are matched incorrectly. A value of maxDist = 3 produces 54 matches only two of which (Heavy Surf and Cold) are matched incorrectly.

``` r
#Create an ordered data frame called matching for the matched events
matching <- data.frame(Event = levels(stormData$EventType), MatchedEvent = events[amatch(levels(stormData$EventType), events, maxDist = 3)])
matching$MatchedEvent <- addNA(matching$MatchedEvent)
matching$Event <- as.character(matching$Event)
matching$MatchedEvent <- as.character(matching$MatchedEvent)
matching <- arrange(matching, matching$MatchedEvent, matching$Event)
```

The results of the matching process can be seen below.

``` r
print(matching)
```

    ##                         Event             MatchedEvent
    ## 1       Astronomical Low Tide    Astronomical Low Tide
    ## 2                   Avalanche                Avalanche
    ## 3                    Blizzard                 Blizzard
    ## 4               Coastal Flood            Coastal Flood
    ## 5            Coastal Flooding            Coastal Flood
    ## 6            Coastal FloodING            Coastal Flood
    ## 7             Cold/Wind Chill          Cold/Wind Chill
    ## 8                   Dense Fog                Dense Fog
    ## 9                 Dense Smoke              Dense Smoke
    ## 10                    Drought                  Drought
    ## 11                 Dust Devil               Dust Devil
    ## 12                 Dust Storm               Dust Storm
    ## 13             Excessive Heat           Excessive Heat
    ## 14    Extreme Cold/Wind Chill  Extreme Cold/Wind Chill
    ## 15                Flash Flood              Flash Flood
    ## 16                       Cold                    Flood
    ## 17                      Flood                    Flood
    ## 18               Freezing Fog             Freezing Fog
    ## 19               Frost/Freeze             Frost/Freeze
    ## 20               Funnel Cloud             Funnel Cloud
    ## 21                       Hail                     Hail
    ## 22                       Heat                     Heat
    ## 23                 Heavy Rain               Heavy Rain
    ## 24                 Heavy Snow               Heavy Snow
    ## 25                 Heavy Surf               Heavy Snow
    ## 26                  High Surf                High Surf
    ## 27                  High Wind                High Wind
    ## 28                 High WindS                High Wind
    ## 29                  Ice Storm                Ice Storm
    ## 30           Lake-Effect Snow         Lake-Effect Snow
    ## 31           Lake Effect Snow         Lake-Effect Snow
    ## 32            Lakeshore Flood          Lakeshore Flood
    ## 33                  Lightning                Lightning
    ## 34                Marine Hail              Marine Hail
    ## 35           Marine High Wind         Marine High Wind
    ## 36         Marine Strong Wind       Marine Strong Wind
    ## 37   Marine Thunderstorm Wind Marine Thunderstorm Wind
    ## 38                Rip Current              Rip Current
    ## 39               Rip CurrentS              Rip Current
    ## 40                     Seiche                   Seiche
    ## 41           Storm Surge/Tide         Storm Surge/Tide
    ## 42                Strong Wind              Strong Wind
    ## 43               Strong Winds              Strong Wind
    ## 44               Strong WindS              Strong Wind
    ## 45          Thunderstorm Wind        Thunderstorm Wind
    ## 46                    Tornado                  Tornado
    ## 47        Tropical Depression      Tropical Depression
    ## 48             Tropical Storm           Tropical Storm
    ## 49                    Tsunami                  Tsunami
    ## 50               Volcanic Ash             Volcanic Ash
    ## 51                 Waterspout               Waterspout
    ## 52                   Wildfire                 Wildfire
    ## 53               Winter Storm             Winter Storm
    ## 54             Winter Weather           Winter Weather
    ## 55        AGRICULTURAL FREEZE                     <NA>
    ## 56     ASTRONOMICAL HIGH TIDE                     <NA>
    ## 57              Beach Erosion                     <NA>
    ## 58                  BLACK ICE                     <NA>
    ## 59               BLOWING DUST                     <NA>
    ## 60               blowing snow                     <NA>
    ## 61                 BRUSH FIRE                     <NA>
    ## 62  COASTAL  FloodING/EROSION                     <NA>
    ## 63            COASTAL EROSION                     <NA>
    ## 64   Coastal FloodING/EROSION                     <NA>
    ## 65              Coastal Storm                     <NA>
    ## 66              COASTAL STORM                     <NA>
    ## 67                       COLD                     <NA>
    ## 68              COLD AND SNOW                     <NA>
    ## 69           Cold Temperature                     <NA>
    ## 70               COLD WEATHER                     <NA>
    ## 71                  DAM BREAK                     <NA>
    ## 72            Damaging Freeze                     <NA>
    ## 73            DAMAGING FREEZE                     <NA>
    ## 74                  DOWNBURST                     <NA>
    ## 75                   DROWNING                     <NA>
    ## 76             DRY MICROBURST                     <NA>
    ## 77                Early Frost                     <NA>
    ## 78         Erosion/Cstl Flood                     <NA>
    ## 79             EXCESSIVE SNOW                     <NA>
    ## 80              Extended Cold                     <NA>
    ## 81               Extreme Cold                     <NA>
    ## 82               EXTREME COLD                     <NA>
    ## 83          EXTREME WINDCHILL                     <NA>
    ## 84           FALLING SNOW/ICE                     <NA>
    ## 85          Flash Flood/Flood                     <NA>
    ## 86          Flood/FLASH/Flood                     <NA>
    ## 87                        FOG                     <NA>
    ## 88                     Freeze                     <NA>
    ## 89                     FREEZE                     <NA>
    ## 90           Freezing drizzle                     <NA>
    ## 91           Freezing Drizzle                     <NA>
    ## 92           FREEZING DRIZZLE                     <NA>
    ## 93              Freezing Rain                     <NA>
    ## 94              FREEZING RAIN                     <NA>
    ## 95             Freezing Spray                     <NA>
    ## 96                      FROST                     <NA>
    ## 97                      Glaze                     <NA>
    ## 98                      GLAZE                     <NA>
    ## 99              gradient wind                     <NA>
    ## 100             Gradient wind                     <NA>
    ## 101             GRADIENT WIND                     <NA>
    ## 102                GUSTY WIND                     <NA>
    ## 103           GUSTY WIND/Hail                     <NA>
    ## 104       GUSTY WIND/HVY RAIN                     <NA>
    ## 105           Gusty wind/rain                     <NA>
    ## 106               Gusty Winds                     <NA>
    ## 107               GUSTY WINDS                     <NA>
    ## 108               HARD FREEZE                     <NA>
    ## 109            HAZARDOUS SURF                     <NA>
    ## 110                 Heat Wave                     <NA>
    ## 111      Heavy Rain/High Surf                     <NA>
    ## 112                HEAVY SEAS                     <NA>
    ## 113         Heavy Snow shower                     <NA>
    ## 114                HEAVY SURF                     <NA>
    ## 115       Heavy surf and wind                     <NA>
    ## 116      HEAVY SURF/High Surf                     <NA>
    ## 117                 HIGH SEAS                     <NA>
    ## 118        High Surf ADVISORY                     <NA>
    ## 119               HIGH SWELLS                     <NA>
    ## 120                HIGH WATER                     <NA>
    ## 121           High Wind (G40)                     <NA>
    ## 122                 HURRICANE                     <NA>
    ## 123         Hurricane Edouard                     <NA>
    ## 124         HURRICANE/TYPHOON                     <NA>
    ## 125     HYPERTHERMIA/EXPOSURE                     <NA>
    ## 126      Hypothermia/Exposure                     <NA>
    ## 127      HYPOTHERMIA/EXPOSURE                     <NA>
    ## 128               ICE ON ROAD                     <NA>
    ## 129                 ICE ROADS                     <NA>
    ## 130                 ICY ROADS                     <NA>
    ## 131          LAKE EFFECT SNOW                     <NA>
    ## 132                 LANDSLIDE                     <NA>
    ## 133                LANDSLIDES                     <NA>
    ## 134                 Landslump                     <NA>
    ## 135                 LANDSPOUT                     <NA>
    ## 136          LATE SEASON SNOW                     <NA>
    ## 137       LIGHT FREEZING RAIN                     <NA>
    ## 138                Light snow                     <NA>
    ## 139                Light Snow                     <NA>
    ## 140                LIGHT SNOW                     <NA>
    ## 141            Light Snowfall                     <NA>
    ## 142           Marine Accident                     <NA>
    ## 143  MARINE Thunderstorm Wind                     <NA>
    ## 144                Microburst                     <NA>
    ## 145              MIXED PRECIP                     <NA>
    ## 146       Mixed Precipitation                     <NA>
    ## 147       MIXED PRECIPITATION                     <NA>
    ## 148                 MUD SLIDE                     <NA>
    ## 149                  Mudslide                     <NA>
    ## 150                  MUDSLIDE                     <NA>
    ## 151                 Mudslides                     <NA>
    ## 152    NON-SEVERE WIND DAMAGE                     <NA>
    ## 153     NON-Thunderstorm Wind                     <NA>
    ## 154     NON Thunderstorm Wind                     <NA>
    ## 155                     Other                     <NA>
    ## 156                     OTHER                     <NA>
    ## 157                      RAIN                     <NA>
    ## 158                 RAIN/SNOW                     <NA>
    ## 159               RECORD Heat                     <NA>
    ## 160               RIVER Flood                     <NA>
    ## 161            River Flooding                     <NA>
    ## 162            RIVER FloodING                     <NA>
    ## 163                ROCK SLIDE                     <NA>
    ## 164                ROGUE WAVE                     <NA>
    ## 165                ROUGH SEAS                     <NA>
    ## 166                ROUGH SURF                     <NA>
    ## 167                SMALL Hail                     <NA>
    ## 168                      Snow                     <NA>
    ## 169                      SNOW                     <NA>
    ## 170              SNOW AND ICE                     <NA>
    ## 171               SNOW SQUALL                     <NA>
    ## 172              Snow Squalls                     <NA>
    ## 173              SNOW SQUALLS                     <NA>
    ## 174               STORM SURGE                     <NA>
    ## 175              THUNDERSTORM                     <NA>
    ## 176            Tidal Flooding                     <NA>
    ## 177            TIDAL FloodING                     <NA>
    ## 178       Torrential Rainfall                     <NA>
    ## 179                   TYPHOON                     <NA>
    ## 180         Unseasonable Cold                     <NA>
    ## 181         UNSEASONABLY COLD                     <NA>
    ## 182         UNSEASONABLY WARM                     <NA>
    ## 183           UNSEASONAL RAIN                     <NA>
    ## 184      URBAN/SML STREAM FLD                     <NA>
    ## 185              WARM WEATHER                     <NA>
    ## 186            WET MICROBURST                     <NA>
    ## 187                 Whirlwind                     <NA>
    ## 188                 WHIRLWIND                     <NA>
    ## 189          WILD/FOREST FIRE                     <NA>
    ## 190                      Wind                     <NA>
    ## 191                      WIND                     <NA>
    ## 192             WIND AND WAVE                     <NA>
    ## 193               Wind Damage                     <NA>
    ## 194                     WINDS                     <NA>
    ## 195        Winter Weather MIX                     <NA>
    ## 196        Winter Weather/MIX                     <NA>
    ## 197                Wintry Mix                     <NA>
    ## 198                WINTRY MIX                     <NA>

Note that there are still many events without a match however it was decided to keep with the above matching for two reasons. Firstly, when a larger value was used the number of incorrectly matched events increased dramatically. Secondly, as will be demostrated later, when the number of fatalities, injuries etc were summed over these matched events, the top ten events accounted for large propertions of the totals. Thus since we are concered with which events have the greatest impact, it suffices to report only on the top ten events for each metric. So we assign these matches.

``` r
#Assign the matches
for(i in 1:length(matching$Event)){
    if(is.na(matching[i,2]) == FALSE){
      levels(stormData$EventType)[levels(stormData$EventType) == as.character(matching[i,1])] <- matching[i,2]
    }
}
```

Further Aggregation
-------------------

We next aggregate the data for each of the matched events and examine the top 10. We do this by building three functions, all of which can take 6 inputs: "Fatalities", "Injuries", "TotalInjuriesFatalities", "RealPropertyDamage", "RealCropDamage", "TotalDamage". The output of these funcitons is a dataframe with a name which corresponds to the input.

1.  AggregateByEvent: Subsets the storm data to only include entries where the input is positive, then aggregates by event type.
2.  Top10: Sorts a data frame y by the input then subsets to only include the top ten enties.
3.  ModifyTop10: Adds a column to the data frame z which is a factor corresponding to the input. It also renames the columns.

``` r
AggregateByEvent <- function(input = c("Fatalities", "Injuries", "TotalInjuriesFatalities", "RealPropertyDamage", "RealCropDamage", "TotalDamage")){
  #Filter so that we only have non-zero entries for the column of interest
  x <- stormData[stormData[input] > 0,] %>%
    droplevels()
  #Aggregate by event type and store in a variable named the same as the input
  y <- aggregate(x[[input]], by = list(EventType = x$EventType), FUN = sum)
  colnames(y)[2] <- input
  y
  #out <- assign(input, y)
  #out
}

Top10 <- function(y, input = c("Fatalities", "Injuries", "TotalInjuriesFatalities", "RealPropertyDamage", "RealCropDamage", "TotalDamage")){
  #Order the data frame y by the iput and subset to top 10
  x <- y[order(y[[input]], decreasing = TRUE),]
  z <- x[1:10,] %>%
    droplevels()
  z
 #out <- assign(paste(input, "Top10", sep= ""), z)
 #out
}

ModifyTop10 <- function(z, input = c("Fatalities", "Injuries", "TotalInjuriesFatalities", "RealPropertyDamage", "RealCropDamage", "TotalDamage")){
  #Add a factor column corresponding to input
  x <- z %>% cbind(factor(rep(input, 10)))
  #Rename columns and reassign to input
  colnames(x)[2:3] <- c("Frequency", "Type")
  x
  #out <- assign(paste(input, "Top10", sep= ""), x)
  #out
}
```

We now build the 6 dataframes containing the top 10 severe weather events corresponding to injuries, fatalities, total injuries/fatalities, property damage, crop damage and total damage.

``` r
#Apply the three functions to the population health data
FatalitiesTop10 <- AggregateByEvent(input = "Fatalities") %>% Top10(input = "Fatalities") %>% ModifyTop10(input = "Fatalities")
InjuriesTop10 <- AggregateByEvent(input = "Injuries") %>% Top10(input = "Injuries") %>% ModifyTop10(input = "Injuries")
TotalInjuriesFatalitiesTop10 <- AggregateByEvent(input = "TotalInjuriesFatalities") %>% Top10(input = "TotalInjuriesFatalities") %>% ModifyTop10(input = "TotalInjuriesFatalities")

#Apply the three functions to the economic data
RealPropertyDamageTop10 <- AggregateByEvent(input = "RealPropertyDamage") %>% Top10(input = "RealPropertyDamage") %>% ModifyTop10(input = "RealPropertyDamage")
RealCropDamageTop10 <- AggregateByEvent(input = "RealCropDamage") %>% Top10(input = "RealCropDamage") %>% ModifyTop10(input = "RealCropDamage")
TotalDamageTop10 <- AggregateByEvent(input = "TotalDamage") %>% Top10(input = "TotalDamage") %>% ModifyTop10(input = "TotalDamage")
```

Note how the top ten events account for a large proportion of the totals for all six categories providing justification for the way the earlier matching was performed.

``` r
# Proportion of fatalities accounted for by the top 10 events
(sum(FatalitiesTop10$Frequency) / sum(AggregateByEvent("Fatalities")$Fatalities)) * 100
```

    ## [1] 78.73377

``` r
# Proportion of injuries accounted for by the top 10 events
(sum(InjuriesTop10$Frequency) / sum(AggregateByEvent("Injuries")$Injuries)) * 100
```

    ## [1] 85.60199

``` r
# Proportion of total fatalities and injuriesaccounted for by the top 10 events
(sum(TotalInjuriesFatalitiesTop10$Frequency) / sum(AggregateByEvent("TotalInjuriesFatalities")$TotalInjuriesFatalities) * 100)
```

    ## [1] 83.95875

``` r
# Proportion of crop damage accounted for by the top 10 events
(sum(RealCropDamageTop10$Frequency) / sum(AggregateByEvent("RealCropDamage")$RealCropDamage)) * 100
```

    ## [1] 91.09434

``` r
# Proportion of property damage accounted for by the top 10 events
(sum(RealPropertyDamageTop10$Frequency) / sum(AggregateByEvent("RealPropertyDamage")$RealPropertyDamage)) * 100
```

    ## [1] 93.6531

``` r
# Proportion of total crop and property damage accounted for by the top 10 events
(sum(TotalDamageTop10$Frequency) / sum(AggregateByEvent("TotalDamage")$Total)) * 100
```

    ## [1] 91.84054

We can now combine these 6 data frames into two data frames, one for the population health data and one for the economic data.

``` r
#Combine the data frames into HealthData dataframe
HealthData <- rbind(FatalitiesTop10, InjuriesTop10, TotalInjuriesFatalitiesTop10)

#Combine the data frames into EconomicData dataframe
EconomicData <- rbind(RealCropDamageTop10, RealPropertyDamageTop10, TotalDamageTop10)
```

Data Visualisation
==================

Finally we can make the two plots to answer the two original questions.

![alt]({{ site.url }}{{ site.baseurl }}/images/Storm images/plot1-1.png)

![alt]({{ site.url }}{{ site.baseurl }}/images/Storm images/plot2-1.png)
